name: b64 key, no newlines / gcp
on:
  push:
    branches:
      - 'master'
jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY_NONEWLINES }}
    - name: List gcp config
      run: gcloud config list
