name: Deploy Python Cloud Functions
on:
  push:
    branches:
    - master
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
jobs:
  deploy-loader-functions:
    name: Deploy ftw loader functions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - name: Deploy core loader functions
      run: |
        cd ftw/ftw_pyfns && \
        gcloud functions deploy --region ${GCP_REGION} \
          --project ${GCP_PROJECT} --trigger-http \
          --runtime python37 check_membership

