name: FTW Deploy Study
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCP_PROJECT}}
          APPLICATION_CREDENTIALS: ${{secrets.GCP_SA_JSON}}
        with:
          args: app deploy app.yaml
