name: FTW Deploy Study

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: clarify

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build:webpack
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: studyuidist
          path: ftw/ftw_ui/dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: studyuidist
          path: ftw/ftw_ui/dist
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID
      - name: Deploy
        run: |
          cd ftw/ftw_ui && gcloud app deploy app.yaml
