name: FTW Deploy Study
on:
  push:
    branches:
    - master
env:
  PROJECT_ID: clarify
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd ftw/ftw_ui && yarn install
      - name: Build
        run: cd ftw/ftw_ui && yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ftw/ftw_ui/server
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: ftw/ftw_ui/server
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID
      - name: Deploy
        run: |
          cd ftw/ftw_ui && gcloud app deploy server/app.yaml
