name: gcp notrailing
on:
  push:
    branches:
      - 'master'
jobs:
  json:
    name: JSON
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_SA_KEY_TRAILING }}
        service_account_key: ${{ secrets.GCP_SA_KEY_TRAILING }}
    - name: List gcp config
      run: gcloud config list
